import localFont from "next/font/local";
import "./globals.css";
import Navigation from "@/components/Nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: {
    template: " %s | Investment Bank",
    default: "Investment Bank"
  },
  description: "Generated by create cbogit27",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation/>
        {children}
        <footer className="mt-auto text-center py-16">footer</footer>
      </body>
    </html>
  );
}
